### ISSUE TITLE
JMX To Prom Exporter - More Inclusive Table Naming

### ISSUE THREAD

**Issue by Ferix9288** [apache/pinot#10138]
# The Issue 

For our company usecase, we actually use UUIDs for our table names. Ex: cfec8068-c04e-4131-8c29-1e4850b5c015_OFFLINE

However, the current JMX Prom Java agent config looks like below: 

```
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.segmentsInErrorState.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_segmentsInErrorState_$3"
  cache: true
  labels:
    table: "$1"
    tableType: "$2"
```

`w+` unfortunately does not encapsulate the `-` in the table name, therefore causing us to lose metrics for all of these tables as it fails the regex. This in turn means we lose invaluable metrics which we would like alerts on.

## The Proposal

PR incoming but effectively changing all instances of `((\w+)_(\\w+)` to `(\\S+)_(\\w+)`. In this way, it will accept all non-whitespace characters as a valid name for a table. I do understand that Pinot has exceptions on using `.` in table names, but APIs will cleanse / ensure those table names are sanitized to w/e standard. Hence, if a table name is guaranteed to be clean, it should be properly exported and why I suggest the more flexible regex.
