### ISSUE TITLE
Question about the Helm Chart release

### ISSUE THREAD

**Issue by imalik8088** [apache/pinot#10689]
Hi there, 

I'm running Pinot in Kubernetes via Helm. I've created an own chart which is depending on the [index.yaml](https://github.com/apache/pinot/blob/master/kubernetes/helm/index.yaml): 

```yaml
apiVersion: v2
name: apache-pinot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: pinot
    repository: https://raw.githubusercontent.com/apache/pinot/master/kubernetes/helm
    version: 0.2.6
```

The issue that I'm facing is that I want to expose Pinot in my k8s cluster via ingress resource and the ingress used in the version `0.2.6` uses an old apiVersion which is deprecated and not anymore applicable.

Are any plans to release a newer version of the chart? The mentioned ingress issue has been already resolved in the master but I'm not able to use it in the mentioned `0.2.6` release.
