### ISSUE TITLE
Configuration values for data directories are merged when running a pinot controller

### ISSUE THREAD

**Issue by estebanz01** [apache/pinot#12689]
While working on #12547 I found out that if I have the following helm configuration:

```yaml
controller:
  data:
    dir: /var/pinot/data

  # ... more configs
  extra:
    configs: |-
      controller.data.dir=s3://my-bucket/folder
```

The pinot controller will save the data in `/var/pinot/data/s3:///my-bucket/folder` within the attached PVC or within the pod, depending on how you configure the storage. I managed to replicate the same behaviour with the following helm config:

```yaml
controller:
  # ... more configs
  extra:
    configs: |-
      controller.data.dir=/var/pinot/folder
      controller.data.dir=/var/pinot/other/folder
```

ended up with data being saved in `/var/pinot/folder/var/pinot/other/folder`.

I think the behaviour should be to override and use latest seen configuration instead. Let me know if that's expected and if I should close this issue.

Thanks!
