### ISSUE TITLE
Temporal overlap of anomalous events

### ISSUE THREAD

**Issue by JohnTheLearner** [apache/pinot#4676]
I noticed anomalous event overlaps while running ThirdEye over the demo data.  Configuration parameters are available to specify if, and how large, gaps between anomalous events are allowed to be, but anomalous events should be exclusive of each other (no temporal overlap).

### Overlap (zoomed)
In the below example, the 8/18 and 8/23 events overlap by ~ 2 days:
![TE overlap - zoomed in](https://user-images.githubusercontent.com/9376440/66167196-b3a28980-e5f6-11e9-95e1-c447d8f140fe.png)

### Time Range
Since the demo data is generated each time it’s run, I doubt the time range is significant, but here is the range I observed during this case (this wasn't the only observation of this, though):
![TE overlap - time range](https://user-images.githubusercontent.com/9376440/66166420-8359eb80-e5f4-11e9-9170-f4d8afd8058f.png)

### Entire Preview 
...when setting-up the detection via `http://localhost:51426/app/#/self-serve/create-alert` was:  
![TE overlap - zoomed out](https://user-images.githubusercontent.com/9376440/66166543-d6cc3980-e5f4-11e9-96e0-50f94d2cca35.png)

### Detection Configuration 
...that generated the above output:
```
# Below is a sample template. You may refer the documentation for more examples and update the fields accordingly.

# Give a name for this anomaly detection pipeline (should be unique).
detectionName: detection_test_1

# Tell the alert recipients what it means if this alert is fired.
description: If this alert fires then it means so-and-so and check so-and-so for irregularities

# The metric you want to do anomaly detection on. You may type a few characters and look ahead (ctrl + space) to auto-fill.
metric: purchases

# The dataset or UMP table name to which the metric belongs. Look ahead should auto populate this field.
dataset: business

rules:
- detection:
   - name: detection_rule_1
     type: PERCENTAGE_RULE
     params:
       offset: do1d
       percentageChange: 0.01

- detection:
   - name: detection_rule_2
     type: THRESHOLD
     params:
       min: 140
```
