### ISSUE TITLE
[TE] ThirdEye doesn't update Anomalies after editing alert

### ISSUE THREAD

**Issue by suvodeep-pyne** [apache/pinot#5831]
ThirdEye still shows old detected anomalies after the 'alert' is updated.

Steps to reproduce:
1. Load a dataset in TE
2. Create an alert. Say `PERCENTAGE_RULE` so that it generates an anomaly
3. Update the alert. Example, Increase the threshold.
4. After successful update, the overview still shows the old anomalies, while the preview shows the new anomalies.

Example alert:
```
detectionName: pc
description: Capture percentage change in values.

# Tip: Type a few characters and look ahead (ctrl + space) to auto-fill.
metric: views
dataset: pageviews

# Configure multiple rules with "OR" relationship.
rules:
- detection:
  - name: detection_rule_1
    type: PERCENTAGE_RULE             # Configure the detection type here. See doc for more details.
    params:                     # The parameters for this rule. Different rules have different params.
      offset: wo1w
      percentageChange: 0.1 # Change the threshold to alter the set of anomalies.
      # pattern: down.  # Can be used to capture cases only when metric goes down.

```
