### ISSUE TITLE
[K8s] Differentiate match labels between headless and non-headless services

### ISSUE THREAD

**Issue by pedro93** [apache/pinot#7380]
Currently for all resources Pinot has 2 `Service` resources, a headless and non-headless respectively. 

Both services are using the same helper method for the match labels:
```
metadata:
  name: {{ template "pinot.broker.headless" . }}
  labels:
    {{- include "pinot.brokerLabels" . | nindent 4 }}
```

This leads to a duplication of metrics when trying to use Prometheus. 
The solution to this is to make the labels unique, one such approach is to append the `app` label in the headless service with a suffix, i.e: `-headless`, like so:
```
  labels:
    app: {{ include "pinot.name" . }}-headless
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.broker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

**Comment by ddcprg** [comment]
IMHO metrics should be pulled per pod instead of per service. I'm curious to know how you configure Prometheus to use labels instead of annotations and the reason to pull metrics from the service instead of  the pod. Cheers!

**Comment by pedro93** [comment]
We have defined a ServiceMonitor resource to tell prometheus what to scrape:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: data
    release: op
  name: {{ template "pinot.fullname" . }}
  namespace: dc-pinot
spec:
  endpoints:
  - targetPort: 8080
    path: /metrics
  namespaceSelector:
    matchNames:
    - dc-pinot
  selector:
    matchLabels:
      app: {{ template "pinot.name" . }}
```

The issue comes into play with the `matchLabels` selector. Perhaps we are not defining the appropriate selector?
