### ISSUE TITLE
Difference between repo and docs

### ISSUE THREAD

**Issue by zhixun-luy** [apache/pinot#8698]
ThirdEye repo moved to https://github.com/project-thirdeye/thirdeye
And Pinot docs: 1: Update the data sources configuration
       Insert the connector configuration for Pinot in thirdeye-pinot/config/data-sources/data-sources-config.yml.
But data-sources-config.yml is in "thirdeye-dashboard/config/data-sources/data-sources" folder.
This is one issue of all I've found some differences in docs.
Is there a correct link to doc or ThirdEye?
![image](https://user-images.githubusercontent.com/52573631/168379141-85c09fa2-1c1b-4f96-a594-7cd891b344d6.png)

**Comment by zhixun-luy** [comment]
https://thirdeye.readthedocs.io/en/latest/index.html
It's showing the example configuration with MySQL, but my data is Pinot data.
I'm trying to set csv data(I've already installed Pinot docker and added this csv as dataset/table) in thirdeye dashboard.
How can I change the configurations for this?

**Comment by Jackie-Jiang** [comment]
@apucher @suvodeep-pyne Can you please take a look at this issue? Is this the up-to-date thrid-eye doc?

**Comment by suvodeep-pyne** [comment]
@Jackie-Jiang we are already chatting with @zhixun-luy on slack.

**Comment by Jackie-Jiang** [comment]
@suvodeep-pyne Thanks! Can you please update this issue with some context (chat history should be fine). Can we close this issue if it is already resolved?

**Comment by zhixun-luy** [comment]
On the slack, it's saying this repo link.

```
1. my use-case is to detect anomaly in my data and create an alert.
2. In the document you shared, there isn't detailed example. I'm using csv data from pinot dataset.
3. How can I get latest version of ThirdEye? What should I do for it?
```

This is my question for ThirdEye integration.
1. How to set pinot data in persistence.yaml file?
2. How to set data-sources-config.yaml file?
I used below config, but failed.
```
dataSourceConfigs:
  - className: org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource
    properties:
      zookeeperUrl: 'localhost:2181'
      clusterName: 'PinotCluster'
      controllerConnectionScheme: 'http'
      controllerHost: '127.0.0.1'
      controllerPort: 9000
      cacheLoaderClassName: org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
    metadataSourceConfigs:
      - className: org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource
```
Any sample configuration for custom pinot data will be helpful.
Thanks.
